apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: kube-dev
  labels:
    app: redis
spec:
  ports:
  - name: redis-port
    port: 6379
  clusterIP: None
  selector:
    app: redis
