kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-dev-pvc
  namespace: kube-dev
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
