apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: monitoring-grafana-ingress
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: grafana.zxc.com
    http:
      paths:
      - backend:
          serviceName: monitoring-grafana
          servicePort: 3000
