apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  namespace: kube-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-ops
  template:
    metadata:
      labels: 
        name: mysql-ops
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.12
          imagePullPolicy: IfNotPresent
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "noc-mysql"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: "/var/lib/mysql"
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
