apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: kube-ops
  labels: 
    name: mysql-svc
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    name: http
    nodePort: 30003
  selector:
    name: mysql-ops
